app_port: 80
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: "us5.datadoghq.com"
datadog_checks:
  http_check:
    instances:
      - name: Redmine
        url: "http://localhost:{{ app_port }}"
        timeout: 5
